name: Firebase Backup

on:
  schedule:
    - cron: '0 * * * *' # Cada hora (ajusta según lo que necesites)
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install firebase-admin

      - name: Run backup script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE }}
        run: node backup.js